name: GitFlow - CI/CD Tienda DevOps 

on:
  push:
    branches: [ "desarrollo_front" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
      - 'backend/**'
      - 'db/**'

jobs:
  build:                          # <- este es el nombre/id del job, falta en tu versión
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # <- el step de checkout necesita 'uses', si no, no hace nada

      - name: Probar pipeline
        run: echo "estoy funcionando"

    