name: GitFlow - CI/CD Tienda DevOps - Frontend(pull request)
on:
  push:
    branches: [ "desarrollo_front" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
      - 'backend/**'
      - 'db/**'
  jobs:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout code
      - run: echo "estoy funcionando"

    